### ISSUE TITLE
Add a Loading Spinner

### ISSUE THREAD

**Issue by ArcadyRob** [ArcadyRob/polar-dash#15]
Implement a loading spinner to display when quiz questions are being fetched to provide visual feedback to users.

**Comment by NawinKumarSharma** [comment]
can you please provide me the path of code where quiz question is managed?

**Comment by ArcadyRob** [comment]
It's still under development. However you can set up the spinner as a re-usable component.

**Comment by jalezi** [comment]
Assign me. 

Is something like [spinning bear head](https://codesandbox.io/p/sandbox/happy-wiles-9nnp5d) ok or would you prefer classic spinner?

There is another issue. Tailwind classes are not working. Importing `'tailwindcss/tailwind.css'` in `layout.tsx` should make it work. Should I open another issue?

**Comment by ArcadyRob** [comment]
bear spinner would be great!

Sure if tailwind is not working then go ahead. feel free to make an issue

**Comment by ArcadyRob** [comment]
I assigned both of you. seems like an issue that can be easily picked up by both of you. good luck amigos!
