### ISSUE TITLE
Establish Basic Design System

### ISSUE THREAD

**Issue by ArcadyRob** [ArcadyRob/polar-dash#25]
To establish a basic design system for our project, which will serve as a foundation for maintaining consistent styles, improving efficiency in development, and ensuring a cohesive user experience.

Tasks:

- Define Color Palette: Create a palette of primary and secondary colors to be used throughout the project. Consider factors like branding, accessibility, and readability.

- Typography: Choose a suitable font family for headings and body text. Define font sizes and line heights for various elements (e.g., headings, paragraphs, lists).

- Spacing and Layout: Establish a consistent spacing system, including margins and paddings, to provide structure and visual balance to our layouts.

- Buttons: Design and define button styles, including default, hover, and active states. Consider different button types (primary, secondary) and how they should be used.

- Form Elements: Define styles for form elements like inputs, textareas, checkboxes, and radio buttons. Include focus and error states.

**Comment by DemienDrost** [comment]
Assign this to me please

**Comment by ArcadyRob** [comment]
good luck @DemienDrost!
